name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: 54.221.95.146
        username: ubuntu
        key: MIIEpAIBAAKCAQEAxQUxjWWE2InKHFKy6LXCM+svqnAczy/bgNr1MLdQx3ZgEsqo
CCALj1R/qeQ2h3FdvZ2L9NFl9s49E+GrSwRqP6uByBcDNHfDDTjSaP27B5ROQj7B
Qk0dTBpqXW/ZVWQqswIZGbO62EBSanQmcgjAtrFyiQdpy0Vidq/0CTBrRWxMCJww
wDq0ncX6n5mzmTjDqbGXpXCqnfW9rhLIt6AIGYH7RIWUyhsG7FW0CX78HZ0kyY4q
hJisYWYg9NanbDIh48preSS+9SyD5Oo0tAsqTsz/Nx4mNDMW+PymhwpCoMDpR22g
a/pLyfBDhMCgo7RyWASieeWoKSDuIHzP/RmkWwIDAQABAoIBAQC6TM3tiYiUBb9D
BwQ8PtrTo1ngTcFAPV3Pu7xMg5tz8UCppE492Kd1sg5CBRV2/8EHcvmL15IWTjC9
IxCJkDQz3qaLIQ+bxn9/ejKkqwD3Csrxo0u1uRuyAeyATCpzr5Mc0CgSALz2jeQg
25IbFKG+X48RehwU5ZhU6M7W/Z0B99w0uk6VB6shDXBUh3H2X54aqjNCX7ELJFz4
NRJADU0nmXcYnDICamcz78PBW4JPmO9HiINFzlq+Ty1QnX4p1/NSzFgLagjgjsH2
r2sxruzQFizNp0vlptboex3AgpjWMpQbj9nYaC6lmZ7SOWE5Wze2WOGg0OeZSHWt
wlKwWByBAoGBAOH2ff9Q16gU/hGxVqfD/1bEL8Vteu5nQBqnBZzzzfOZwBYK/SHk
2xMCVQ0zwlVph5qCC6rEqOBdazMjazbDyBo5seczY6AHQ4JBuGJJRZ8zIN5JC+zr
eYFzH0fUAvdC7vUO4J+HjCRfaeYMSX0NaKZa4w93z89xOhygbvft/C8bAoGBAN81
yWVApeyrUDv4s6d/JR+0QriTSIjXexiyGiT5HbV7r5NqMMAAZqQOlzOr32Ta/iBY
2jd7OUnlS7QKArRazzV+kKZg88tNxD82OOpRg7KpeuzX5VBTqjGko+ttIqCnvOa9
sSO0/osY4R7kJ5huuUeNR1kPavraDEYjGFBqg3PBAoGAeqsP95zxlkPfMceuHWFf
qsDSlkE67VWMDWwCthP9CHO9Pbo1dUMCUy1+8q3Yn/msLgrPPqOIclUErzxZJd/f
L62GkNbrDKMk2P/Ik0Ln0uc0vre1C6dBzS6sGphUC9uAUfUDqFczk0NhAAxHkOXI
nBbXETyfyiPTwlquI1ZFA2UCgYEA3muBcQTXkhsvi2MK2lgnDQ2aAsS43asi/XvT
843NXd+PGG0TgO+lV8s2PgYBSEW0P1VqtShz8L+tDQ2Anmly2xJwX2py5N5sNLT6
R/vMKQca99E2rzF/gZJWySzp+X7MDH1ve25Kyx6SjS66ifmjZLpSI1vqtWb8HhOw
kclhjcECgYAQRAW1H/2u7VxjEeurUIONMqMc1xIpb/yQ39brhepdO8G06A97OsaW
NAnf0dZC8LCAFROt4n+Bed5wFu7Xbm5rDHTbpnDRHLRfMQDavvEd312cq7L+S06l
5ZRSMnw3a2yJVKM7EVyZ96QtaeyfraVSjjTs2U0WFqac9fTwZkbHQQ==
        script: |
          cd /var/www/html
          git pull origin main
